name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Rust cache
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: Setup Scoop (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: MinoruSekine/setup-scoop@11383f96752fc77f5b26e0d2e51e216250059ccf
      - name: Install Twitch-Cli (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: powershell
        run: |
          scoop bucket add twitch https://github.com/twitchdev/scoop-bucket.git
          scoop install twitch-cli
      - name: Install Twitch-Cli (Linux/macOS)
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: brew install twitchdev/twitch/twitch-cli

      - name: Build
        run: cargo build
      - name: Run clippy
        run: cargo clippy --tests
      - name: Run tests
        run: cargo test
